FROM golang:1.23.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o lightspeed .

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/lightspeed /app/lightspeed

COPY ../configuration.json /app/configuration.json

EXPOSE 53/udp
EXPOSE 8080

ENTRYPOINT ["/app/lightspeed"]
